SELECT TO_CHAR(B.SALES_DATE,'YYYY') AS YEAR,
       EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
       A.GENDER,
       COUNT(DISTINCT B.USER_ID) AS USERS
FROM USER_INFO A
INNER JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
WHERE A.GENDER IS NOT NULL
GROUP BY TO_CHAR(B.SALES_DATE,'YYYY') , EXTRACT(MONTH FROM SALES_DATE) , A.GENDER
ORDER BY YEAR,MONTH, A.GENDER

