-- 코드를 입력하세요
SELECT ANIMAL_ID,NAME from (select A.ANIMAL_ID, A.NAME, TO_CHAR(B.DATETIME, 'YYYYMMDDHH24MISS') - TO_CHAR(A.DATETIME, 'YYYYMMDDHH24MISS') from 
ANIMAL_INS A, ANIMAL_OUTS B
where A.ANIMAL_ID = B.ANIMAL_ID 
              order by TO_CHAR(B.DATETIME, 'YYYYMMDDHH24MISS') - TO_CHAR(A.DATETIME, 'YYYYMMDDHH24MISS') desc)
where rownum <=2