SELECT ITEM_ID,	ITEM_NAME,	RARITY
  FROM ITEM_INFO
 WHERE ITEM_ID IN (SELECT T1.ITEM_ID
                     FROM ITEM_TREE T1
                     LEFT OUTER JOIN ITEM_TREE T2 ON T1.ITEM_ID = T2.PARENT_ITEM_ID
                     WHERE T2.ITEM_ID IS NULL)
ORDER BY 1 DESC

