WITH RENT AS (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE TO_CHAR(START_DATE,'YYYYMM') BETWEEN '202208' AND '202210'
GROUP BY CAR_ID
HAVING COUNT(*) > 4 )

SELECT EXTRACT(MONTH FROM START_DATE) MONTH , CAR_ID , COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(START_DATE,'YYYYMM') BETWEEN '202208' AND '202210'
AND CAR_ID IN (SELECT * FROM RENT)
GROUP BY EXTRACT(MONTH FROM START_DATE),CAR_ID
ORDER BY MONTH , CAR_ID DESC

