SELECT T1.PRODUCT_CODE, (T1.PRICE * T2.SALES_AMOUNT) AS SALES
  FROM PRODUCT T1
     , (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
  FROM OFFLINE_SALE 
 GROUP BY PRODUCT_ID)T2
 WHERE T1.PRODUCT_ID = T2.PRODUCT_ID
 ORDER BY SALES DESC, T1.PRODUCT_CODE




  