-- 코드를 입력하세요

SELECT UGU.USER_ID , UGU.NICKNAME,
       UGU.CITY || ' ' || STREET_ADDRESS1 ||' ' || STREET_ADDRESS2 AS "전체주소" , 
       SUBSTR(TLNO,0,3)||'-'||SUBSTR(TLNO,4,4)||'-'||SUBSTR(TLNO,8,4) AS "전화번호"
FROM USED_GOODS_USER UGU, (
    SELECT WRITER_ID , COUNT(*)
        FROM USED_GOODS_BOARD UGB
        GROUP BY UGB.WRITER_ID
        HAVING COUNT(*) >= 3
) UGB
WHERE UGU.USER_ID = UGB.WRITER_ID 
ORDER BY UGU.USER_ID DESC
