SELECT YEAR, MONTH, GENDER, COUNT(DISTINCT USER_ID) AS USERS
  FROM (SELECT TO_CHAR(T2.SALES_DATE,'YYYY') AS YEAR
             , TO_NUMBER(TO_CHAR(T2.SALES_DATE,'MM')) AS MONTH
              , T1.GENDER
        , T1.USER_ID
           FROM USER_INFO T1
              , ONLINE_SALE T2
          WHERE T1.USER_ID = T2.USER_ID
            AND T1.GENDER IS NOT NULL)
 GROUP BY  YEAR, MONTH, GENDER
 ORDER BY  YEAR, MONTH, GENDER
  
  
 






