-- 코드를 입력하세요

SELECT UGU.USER_ID, UGU.NICKNAME, UGB.TOTAL_SALES
FROM USED_GOODS_USER UGU, (
SELECT WRITER_ID , SUM(PRICE) AS TOTAL_SALES , STATUS
FROM USED_GOODS_BOARD 
GROUP BY WRITER_ID , STATUS
HAVING SUM(PRICE) >= 700000 ) UGB
WHERE UGU.USER_ID = UGB.WRITER_ID
AND UGB.STATUS = 'DONE'
ORDER BY UGB.TOTAL_SALES