SELECT FLAVOR 
  FROM (SELECT T1.TOTAL_ORDER + T2.TOTAL_ORDER AS TOTAL_ORDER, T1.FLAVOR
  FROM (SELECT FLAVOR 
             , SUM(TOTAL_ORDER) AS TOTAL_ORDER
          FROM JULY
         GROUP BY FLAVOR) T1
     , FIRST_HALF T2
 WHERE T1.FLAVOR = T2.FLAVOR
 ORDER BY TOTAL_ORDER DESC
  )
  WHERE ROWNUM < 4

 