WITH TIME AS (SELECT LEVEL - 1 AS HOUR 
  FROM DUAL CONNECT BY LEVEL <= 24)
SELECT T1.HOUR, NVL(COUNT,0) AS COUNT
  FROM TIME T1
     , (SELECT TO_NUMBER(TO_CHAR(DATETIME,'HH24')) AS HOUR , COUNT(1) AS COUNT
  FROM ANIMAL_OUTS
 GROUP BY TO_NUMBER(TO_CHAR(DATETIME,'HH24'))) T2
WHERE T1.HOUR = T2.HOUR (+)
ORDER BY T1.HOUR
     

     



 
  