SELECT CASE WHEN SUM( CASE WHEN T1.CATEGORY = 'Front End' THEN 1 ELSE 0 END ) > 0
             AND SUM( CASE WHEN T1.NAME = 'Python' THEN 1 ELSE 0 END ) > 0 THEN 'A' 
            WHEN SUM( CASE WHEN T1.NAME = 'C#' THEN 1 ELSE 0 END ) > 0 THEN 'B'
            WHEN SUM( CASE WHEN T1.CATEGORY = 'Front End' THEN 1 ELSE 0 END ) > 0 THEN 'C' END AS GRADE
     , T2.ID
     , T2.EMAIL
  FROM SKILLCODES T1
 LEFT OUTER JOIN DEVELOPERS T2 ON T1.CODE & T2.SKILL_CODE
 GROUP BY T2.ID, T2.EMAIL
 HAVING GRADE IS NOT NULL
 ORDER BY GRADE, T2.ID